In [1]:
# Import Python libraries for data manipuation and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot

# Import the Python machine learning libraries we need
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [2]:
# Load the data set
dataset = pd.read_excel("data.xlsx")

In [3]:
# Inspect first few rows
dataset.head(12)

R1  R2  R3  R4  R5  R6  R7  R8  I1  I2  ...  E8  C1  C2  C3  C4  C5  C6  \
0    5   3   5   4   3   5   2   3   5   5  ...   5   1   3   3   1   3   2   
1    4   5   5   5   3   5   4   3   3   3  ...   4   3   4   4   2   4   4   
2    5   2   2   4   1   3   2   2   3   3  ...   3   2   2   4   3   3   3   
3    4   4   2   4   4   4   5   4   4   3  ...   3   4   4   5   3   4   5   
4    5   4   5   5   5   5   5   3   4   4  ...   4   4   5   4   4   5   5   
5    3   3   1   5   4   5   4   4   2   4  ...   4   1   5   2   1   1   3   
6    4   4   4   4   4   5   4   5   5   4  ...   4   2   2   2   1   3   5   
7    5   3   1   1   1   1   3   3   5   1  ...   5   4   3   2   3   5   5   
8    3   1   2   2   1   2   2   1   4   4  ...   4   3   3   3   3   3   2   
9    2   4   2   5   1   4   3   2   5   5  ...   2   1   3   2   2   2   4   
10   1   2   1   3   2   3   3   2   2   4  ...   4   3   2   2   2   2   3   
11   5   5   3   5   2   3   3   3   4   3  ...   4   3   5   5   4   5   4   

    C7  C8      major  
0    1   1  Realistic  
1    2   3  Realistic  
2    3   3  Realistic  
3    4   4  Realistic  
4    5   4  Realistic  
5    2   2  Realistic  
6    1   2  Realistic  
7    3   3  Realistic  
8    3   2  Realistic  
9    1   2  Realistic  
10   2   2  Realistic  
11   5   2  Realistic  

[12 rows x 49 columns]

In [4]:
# Inspect data shape
dataset.shape

(36775, 49)

In [5]:
# Inspect descriptive stats
dataset.describe()

R1            R2            R3            R4            R5  \
count  36775.000000  36775.000000  36775.000000  36775.000000  36775.000000   
mean       2.618872      2.135228      1.769055      2.330931      1.771747   
std        1.315058      1.222695      1.124123      1.340722      1.066608   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      1.000000      1.000000      1.000000      1.000000   
50%        3.000000      2.000000      1.000000      2.000000      1.000000   
75%        4.000000      3.000000      2.000000      3.000000      2.000000   
max        5.000000      5.000000      5.000000      5.000000      5.000000   

                 R6            R7            R8            I1            I2  \
count  36775.000000  36775.000000  36775.000000  36775.000000  36775.000000   
mean       2.257865      2.038967      1.995622      3.465262      3.414494   
std        1.268960      1.168433      1.168911      1.283806      1.332322   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      1.000000      1.000000      3.000000      2.000000   
50%        2.000000      2.000000      2.000000      4.000000      4.000000   
75%        3.000000      3.000000      3.000000      5.000000      4.000000   
max        5.000000      5.000000      5.000000      5.000000      5.000000   

       ...            E7            E8            C1            C2  \
count  ...  36775.000000  36775.000000  36775.000000  36775.000000   
mean   ...      2.478885      2.714752      2.364432      2.422814   
std    ...      1.297040      1.345290      1.268062      1.235177   
min    ...      1.000000      1.000000      1.000000      1.000000   
25%    ...      1.000000      1.000000      1.000000      1.000000   
50%    ...      2.000000      3.000000      2.000000      2.000000   
75%    ...      3.000000      4.000000      3.000000      3.000000   
max    ...      5.000000      5.000000      5.000000      5.000000   

                 C3            C4            C5            C6            C7  \
count  36775.000000  36775.000000  36775.000000  36775.000000  36775.000000   
mean       2.449218      2.575581      2.656179      2.738029      2.256397   
std        1.300302      1.258761      1.377617      1.300189      1.246886   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      1.000000      1.000000      2.000000      1.000000   
50%        2.000000      3.000000      3.000000      3.000000      2.000000   
75%        3.000000      3.000000      4.000000      4.000000      3.000000   
max        5.000000      5.000000      5.000000      5.000000      5.000000   

                 C8  
count  36775.000000  
mean       2.310129  
std        1.238774  
min        1.000000  
25%        1.000000  
50%        2.000000  
75%        3.000000  
max        5.000000  

[8 rows x 48 columns]

In [6]:
X=dataset.iloc[:, :-1].values
Y=dataset.iloc[:, -1:].values

In [7]:
print(X)

[[5 3 5 ... 2 1 1]
 [4 5 5 ... 4 2 3]
 [5 2 2 ... 3 3 3]
 ...
 [3 3 1 ... 3 2 3]
 [5 4 2 ... 4 2 3]
 [3 3 4 ... 1 2 4]]


In [8]:
print(Y)

[['Realistic']
 ['Realistic']
 ['Realistic']
 ...
 ['Conventional']
 ['Conventional']
 ['Conventional']]


In [9]:
X_train, X_test, Y_train, Y_test =  train_test_split(X, Y, test_size=0.25, random_state=0)

In [10]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X_test

array([[ 0.28778758, -0.11289877, -0.68911273, ...,  0.96445946,
         1.39741908,  1.36734974],
       [ 1.04742669,  0.70481681,  1.09101449, ...,  0.19560703,
         0.59535857,  1.36734974],
       [ 1.80706581,  2.34024796, -0.68911273, ...,  1.73331189,
         1.39741908,  2.17604882],
       ...,
       [-0.47185154, -0.93061434,  1.98107809, ...,  0.96445946,
         1.39741908,  0.55865065],
       [ 0.28778758, -0.93061434,  0.20095088, ...,  0.19560703,
        -1.00876245,  0.55865065],
       [-0.47185154,  0.70481681,  0.20095088, ..., -0.5732454 ,
        -1.00876245, -0.25004843]])

In [12]:
Y_train

array([['Investigative'],
       ['Investigative'],
       ['Investigative'],
       ...,
       ['Social'],
       ['Investigative'],
       ['Realistic']], dtype=object)

In [13]:
Y_test

array([['Social'],
       ['Enterprising'],
       ['Conventional'],
       ...,
       ['Enterprising'],
       ['Investigative'],
       ['Artistic']], dtype=object)

In [14]:
# Training the Random Forest Classification model on the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [15]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [16]:
print(y_pred)

['Investigative' 'Investigative' 'Enterprising' ... 'Investigative'
 'Investigative' 'Investigative']


In [28]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, y_pred))

               precision    recall  f1-score   support

     Artistic       0.28      0.20      0.23       726
 Conventional       0.22      0.11      0.15       446
 Enterprising       0.20      0.13      0.16       759
Investigative       0.55      0.80      0.65      4449
    Realistic       0.43      0.29      0.34      1546
       Social       0.22      0.09      0.12      1268

     accuracy                           0.48      9194
    macro avg       0.32      0.27      0.28      9194
 weighted avg       0.42      0.48      0.43      9194

